// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiquanlynhahang.Data;

#nullable disable

namespace apiquanlynhahang.Migrations
{
    [DbContext(typeof(UngDungDbContext))]
    [Migration("20260328021936_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("apiquanlynhahang.Models.BanAn", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cap_nhat_luc");

                    b.Property<DateTime?>("DangSuDungLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dang_su_dung_luc");

                    b.Property<uint?>("DatBanHienTaiId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("dat_ban_hien_tai_id");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime?>("GiaiPhongLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("giai_phong_luc");

                    b.Property<string>("KhuVucId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("khu_vuc_id");

                    b.Property<bool>("KichHoatQr")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("kich_hoat_qr");

                    b.Property<string>("MaBan")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_ban");

                    b.Property<string>("MaDatBanHienTai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ma_dat_ban_hien_tai");

                    b.Property<string>("MaQr")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_qr");

                    b.Property<uint>("SucChua")
                        .HasColumnType("int unsigned")
                        .HasColumnName("suc_chua");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tao_luc");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ten_ban");

                    b.Property<string>("TokenQr")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_qr");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("KhuVucId");

                    b.HasIndex("MaBan")
                        .IsUnique();

                    b.HasIndex("MaQr")
                        .IsUnique();

                    b.HasIndex("TokenQr")
                        .IsUnique();

                    b.ToTable("ban_an", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.BienDongKho", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("LoaiBienDong")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("loai_bien_dong");

                    b.Property<uint>("NguyenLieuId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("nguyen_lieu_id");

                    b.Property<decimal>("SoLuongSau")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("so_luong_sau");

                    b.Property<decimal>("SoLuongThayDoi")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("so_luong_thay_doi");

                    b.Property<decimal>("SoLuongTruoc")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("so_luong_truoc");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tao_luc");

                    b.Property<uint?>("ThamChieuId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tham_chieu_id");

                    b.Property<string>("ThamChieuLoai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tham_chieu_loai");

                    b.HasKey("Id");

                    b.HasIndex("NguyenLieuId");

                    b.ToTable("bien_dong_kho", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.ChiTietDatBan", b =>
                {
                    b.Property<uint>("DatBanId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("dat_ban_id");

                    b.Property<string>("BanAnId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ban_an_id");

                    b.Property<DateTime>("GanLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("gan_luc");

                    b.HasKey("DatBanId", "BanAnId");

                    b.ToTable("chi_tiet_dat_ban", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.ChiTietDonHang", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("don_gia");

                    b.Property<uint>("DonHangId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("don_hang_id");

                    b.Property<string>("GhiChuMon")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu_mon");

                    b.Property<string>("KichCo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("kich_co");

                    b.Property<string>("MaBienThe")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ma_bien_the");

                    b.Property<uint?>("MonAnId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("mon_an_id");

                    b.Property<uint>("SoLuong")
                        .HasColumnType("int unsigned")
                        .HasColumnName("so_luong");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ten_mon");

                    b.Property<string>("ThongTinMon")
                        .HasColumnType("longtext")
                        .HasColumnName("thong_tin_mon");

                    b.Property<string>("ToppingDaChon")
                        .HasColumnType("longtext")
                        .HasColumnName("topping_da_chon");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.HasIndex("MonAnId");

                    b.ToTable("chi_tiet_don_hang", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.ChiTietNhapKho", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("don_gia_nhap");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<uint>("NguyenLieuId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("nguyen_lieu_id");

                    b.Property<uint>("PhieuNhapKhoId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("phieu_nhap_kho_id");

                    b.Property<decimal>("SoLuongNhap")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("so_luong_nhap");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("thanh_tien");

                    b.HasKey("Id");

                    b.HasIndex("NguyenLieuId");

                    b.HasIndex("PhieuNhapKhoId");

                    b.ToTable("chi_tiet_nhap_kho", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.CongThucMonAn", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cap_nhat_luc");

                    b.Property<decimal>("DinhLuong")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("dinh_luong");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("don_vi_tinh");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<uint>("MonAnId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("mon_an_id");

                    b.Property<uint>("NguyenLieuId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("nguyen_lieu_id");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tao_luc");

                    b.HasKey("Id");

                    b.HasIndex("MonAnId", "NguyenLieuId")
                        .IsUnique();

                    b.ToTable("cong_thuc_mon_an", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.DatBan", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cap_nhat_luc");

                    b.Property<DateTime?>("CheckInLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("check_in_luc");

                    b.Property<string>("DipDacBiet")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dip_dac_biet");

                    b.Property<string>("EmailKhach")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email_khach");

                    b.Property<string>("EmailNguoiDung")
                        .HasColumnType("longtext")
                        .HasColumnName("email_nguoi_dung");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("GhiChuNoiBo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu_noi_bo");

                    b.Property<TimeOnly>("GioDat")
                        .HasColumnType("time(6)")
                        .HasColumnName("gio_dat");

                    b.Property<DateTime?>("HoanThanhLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("hoan_thanh_luc");

                    b.Property<DateTime?>("HuyLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("huy_luc");

                    b.Property<string>("KenhXacNhan")
                        .HasColumnType("longtext")
                        .HasColumnName("kenh_xac_nhan");

                    b.Property<string>("KhuVucUuTien")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("khu_vuc_uu_tien");

                    b.Property<string>("MaDatBan")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_dat_ban");

                    b.Property<DateOnly>("NgayDat")
                        .HasColumnType("date")
                        .HasColumnName("ngay_dat");

                    b.Property<uint?>("NguoiDungId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<string>("NguonTao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nguon_tao");

                    b.Property<string>("SoDienThoaiKhach")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("so_dien_thoai_khach");

                    b.Property<uint>("SoKhach")
                        .HasColumnType("int unsigned")
                        .HasColumnName("so_khach");

                    b.Property<string>("TaoBoi")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tao_boi");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tao_luc");

                    b.Property<string>("TenKhach")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ten_khach");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("VangMatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("vang_mat_luc");

                    b.Property<DateTime?>("XepBanLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("xep_ban_luc");

                    b.HasKey("Id");

                    b.HasIndex("MaDatBan")
                        .IsUnique();

                    b.HasIndex("NguoiDungId");

                    b.ToTable("dat_ban", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.DonHang", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cap_nhat_luc");

                    b.Property<DateTime>("DatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dat_luc");

                    b.Property<string>("DiaChiKhachHang")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dia_chi_khach_hang");

                    b.Property<string>("EmailKhachHang")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email_khach_hang");

                    b.Property<string>("EmailNguoiDung")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email_nguoi_dung");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("MaBan")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ma_ban");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_don_hang");

                    b.Property<string>("MaGiamGiaApDung")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ma_giam_gia_ap_dung");

                    b.Property<uint?>("NguoiDungId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<decimal>("PhiDichVu")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("phi_dich_vu");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phuong_thuc_thanh_toan");

                    b.Property<string>("SoDienThoaiKhachHang")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("so_dien_thoai_khach_hang");

                    b.Property<decimal>("TamTinh")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tam_tinh");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tao_luc");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ten_khach_hang");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("thanh_tien");

                    b.Property<string>("ThongTinKhachHang")
                        .HasColumnType("longtext")
                        .HasColumnName("thong_tin_khach_hang");

                    b.Property<decimal>("TienGiam")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tien_giam");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai_thanh_toan");

                    b.HasKey("Id");

                    b.HasIndex("MaDonHang")
                        .IsUnique();

                    b.HasIndex("NguoiDungId");

                    b.ToTable("don_hang", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.KhuVucBan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cap_nhat_luc");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tao_luc");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ten_khu_vuc");

                    b.HasKey("Id");

                    b.ToTable("khu_vuc_ban", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.MaGiamGia", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime?>("BatDauLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("bat_dau_luc");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cap_nhat_luc");

                    b.Property<uint>("DaSuDung")
                        .HasColumnType("int unsigned")
                        .HasColumnName("da_su_dung");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("dang_hoat_dong");

                    b.Property<decimal>("DonToiThieu")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("don_toi_thieu");

                    b.Property<decimal>("GiaTriGiam")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("gia_tri_giam");

                    b.Property<decimal?>("GiamToiDa")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("giam_toi_da");

                    b.Property<uint?>("GioiHanSuDung")
                        .HasColumnType("int unsigned")
                        .HasColumnName("gioi_han_su_dung");

                    b.Property<DateTime?>("KetThucLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ket_thuc_luc");

                    b.Property<string>("LoaiGiam")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("loai_giam");

                    b.Property<string>("MaGiam")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_giam");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tao_luc");

                    b.Property<string>("TenMaGiam")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ten_ma_giam");

                    b.HasKey("Id");

                    b.HasIndex("MaGiam")
                        .IsUnique();

                    b.ToTable("ma_giam_gia", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.MonAn", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cap_nhat_luc");

                    b.Property<bool>("DangKinhDoanh")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("dang_kinh_doanh");

                    b.Property<string>("DanhMuc")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("danh_muc");

                    b.Property<decimal>("Gia")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hinh_anh");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<string>("NhanMon")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nhan_mon");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tao_luc");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ten_mon");

                    b.Property<string>("ToneMau")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tone_mau");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("mon_an", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.NguoiDung", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cap_nhat_luc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ho_ten");

                    b.Property<string>("MatKhauMaHoa")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mat_khau_ma_hoa");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext")
                        .HasColumnName("so_dien_thoai");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tao_luc");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_dang_nhap");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("vai_tro");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("nguoi_dung", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.NguyenLieu", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cap_nhat_luc");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("don_vi_tinh");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("MaNguyenLieu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ma_nguyen_lieu");

                    b.Property<decimal>("MucCanhBaoToiThieu")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("muc_canh_bao_toi_thieu");

                    b.Property<decimal>("SoLuongTon")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("so_luong_ton");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tao_luc");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ten_nguyen_lieu");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.ToTable("nguyen_lieu", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.PhieuNhapKho", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cap_nhat_luc");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("MaPhieuNhap")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_phieu_nhap");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_nhap");

                    b.Property<uint?>("NguoiTaoId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("nguoi_tao_id");

                    b.Property<string>("NhaCungCap")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nha_cung_cap");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tao_luc");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("tong_tien");

                    b.HasKey("Id");

                    b.HasIndex("MaPhieuNhap")
                        .IsUnique();

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("phieu_nhap_kho", (string)null);
                });

            modelBuilder.Entity("apiquanlynhahang.Models.TokenLamMoi", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cap_nhat_luc");

                    b.Property<DateTime>("HetHanLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("het_han_luc");

                    b.Property<string>("MaBamToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_bam_token");

                    b.Property<uint>("NguoiDungId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tao_luc");

                    b.Property<DateTime?>("ThuHoiLuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thu_hoi_luc");

                    b.HasKey("Id");

                    b.HasIndex("MaBamToken")
                        .IsUnique();

                    b.HasIndex("NguoiDungId");

                    b.ToTable("token_lam_moi", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
